title: "Babylon.js で 3D ゲーム開発を始めよう！"
summary: |-
  本書では、Babylon.js を使って 3D ゲームを開発する方法を解説します。
  Babylon.js は、WebGL/WebGPU を使ってブラウザ上で 3D グラフィックスを描画するためのライブラリです。
  Babylon.js の能力と特徴を理解し、実際にコードを書きながら学んでいきます。

topics:
  - "babylonjs"
  - "webgl"
  - "3d"
  - "typescript"
  - "game"

published: false
price: 0 # FREE!
chapters:
  - what-is-babylonjs
  - comparison
  - playground
  - editor
  - camera-and-light
  - meshes
  - materials
  - shaders
  - importing-assets
  - game-loop
